# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pass' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftyJSON', '~> 4.0'
pod 'ActionKit'
pod 'Alamofire'
pod 'STPopup'
pod 'UITextView+Placeholder'
pod 'JDStatusBarNotification'
pod 'UIScrollView-InfiniteScroll'

end
